CREATE TABLE PUB_USER_INFO(
    USER_ID VARCHAR(32) NOT NULL   COMMENT '用户ID' ,
    USER_NAME VARCHAR(20)    COMMENT '用户名' ,
    PASSWORD VARCHAR(255)    COMMENT '密码' ,
    STATE INT(1)    COMMENT '状态 0正常1冻结' ,
    CREATE_BY VARCHAR(32)    COMMENT '创建人' ,
    CREATE_DATE DATETIME    COMMENT '创建时间' ,
    UPDATE_BY VARCHAR(32)    COMMENT '修改人' ,
    UPDATE_DATE DATETIME    COMMENT '修改时间' ,
    REVISION INT(10)    COMMENT '乐观锁' ,
    PRIMARY KEY (USER_ID)
) COMMENT = '平台用户表 ';/*SQL@Run*/


CREATE TABLE RBAC_GLOBLE_RESOURCE(
    RESOURCE_ID VARCHAR(32) NOT NULL   COMMENT '资源ID' ,
    RESOURCE_PID VARCHAR(32)    COMMENT '资源上级ID' ,
    RESOURCE_URL VARCHAR(100)    COMMENT '资源Url' ,
    RESOURCE_NAME VARCHAR(50)    COMMENT '资源名称' ,
    RESOURCE_TYPE VARCHAR(10)    COMMENT '资源类型 1一级菜单 2二级菜单 3三级菜单' ,
    RESOURCE_SORT INT(10)    COMMENT '排序' ,
    CREATE_BY VARCHAR(32)    COMMENT '创建人' ,
    CREATE_DATE DATETIME    COMMENT '创建时间' ,
    UPDATE_BY VARCHAR(32)    COMMENT '修改人' ,
    UPDATE_DATE DATETIME    COMMENT '修改时间' ,
    REVISION INT(10)    COMMENT '乐观锁' ,
    PRIMARY KEY (RESOURCE_ID)
) COMMENT = '全局资源表 ';/*SQL@Run*/

CREATE TABLE RBAC_RESOURCE(
    RESOURCE_ID VARCHAR(32) NOT NULL   COMMENT '资源ID' ,
    RESOURCE_PID VARCHAR(32)    COMMENT '资源上级ID' ,
    RESOURCE_URL VARCHAR(100)    COMMENT '资源Url' ,
    RESOURCE_NAME VARCHAR(50)    COMMENT '资源名称' ,
    RESOURCE_TYPE VARCHAR(20)    COMMENT '资源类型 1一级菜单 2二级菜单 3三级菜单' ,
    RESOURCE_SORT INT(10)    COMMENT '排序' ,
    TENANT_ID VARCHAR(32)    COMMENT '租户ID' ,
    CREATE_BY VARCHAR(32)    COMMENT '创建人' ,
    CREATE_DATE DATETIME    COMMENT '创建时间' ,
    UPDATE_BY VARCHAR(32)    COMMENT '修改人' ,
    UPDATE_DATE DATETIME    COMMENT '修改时间' ,
    REVISION INT(10)    COMMENT '乐观锁' ,
    PRIMARY KEY (RESOURCE_ID)
) COMMENT = '资源表 ';/*SQL@Run*/

CREATE TABLE RBAC_ROLE(
    ROLE_ID VARCHAR(32) NOT NULL   COMMENT '角色ID' ,
    ROLE_CODE VARCHAR(50)    COMMENT '角色编码' ,
    ROLE_NAME VARCHAR(255)    COMMENT '角色名称' ,
    TENANT_ID VARCHAR(32)    COMMENT '租户ID' ,
    CREATE_BY VARCHAR(32)    COMMENT '创建人' ,
    CREATE_DATE DATETIME    COMMENT '创建时间' ,
    UPDATE_BY VARCHAR(32)    COMMENT '修改人' ,
    UPDATE_DATE DATETIME    COMMENT '修改时间' ,
    REVISION INT(10)    COMMENT '乐观锁' ,
    PRIMARY KEY (ROLE_ID)
) COMMENT = '角色表 ';/*SQL@Run*/

CREATE TABLE RBAC_ROLE_RESOURCE(
    ROLE_ID VARCHAR(32)    COMMENT '角色ID' ,
    RESOURCE_ID VARCHAR(32)    COMMENT '资源ID' ,
    TENANT_ID VARCHAR(32)    COMMENT '租户ID' ,
    CREATE_BY VARCHAR(32)    COMMENT '创建人' ,
    CREATE_DATE DATETIME    COMMENT '创建时间' ,
    UPDATE_BY VARCHAR(32)    COMMENT '修改人' ,
    UPDATE_DATE DATETIME    COMMENT '修改时间' ,
    REVISION INT(10)    COMMENT '乐观锁'
) COMMENT = '角色资源关系表 ';/*SQL@Run*/

CREATE TABLE RBAC_ROLE_DATA(
    ROLE_ID VARCHAR(32)    COMMENT '角色ID' ,
    DATA_ID VARCHAR(32)    COMMENT '数据ID 相关业务数据ID' ,
    DATA_TYPE VARCHAR(20)    COMMENT '数据类型 部门、薪酬' ,
    include_child VARCHAR(1)    COMMENT '是否包含下级 有上下级关系' ,
    TENANT_ID VARCHAR(32)    COMMENT '租户ID' ,
    CREATE_BY VARCHAR(32)    COMMENT '创建人' ,
    CREATE_DATE DATETIME    COMMENT '创建时间' ,
    UPDATE_BY VARCHAR(32)    COMMENT '修改人' ,
    UPDATE_DATE DATETIME    COMMENT '修改时间' ,
    REVISION INT(10)    COMMENT '乐观锁'
) COMMENT = '角色数据关系表 数据：机构节点，数据规则';/*SQL@Run*/

CREATE TABLE RBAC_USER(
    USER_ID VARCHAR(32) NOT NULL   COMMENT '用户ID' ,
    USER_NAME VARCHAR(20)    COMMENT '用户名' ,
    PASSWORD VARCHAR(255)    COMMENT '密码' ,
    TENANT_ID VARCHAR(32)    COMMENT '租户ID' ,
    STATE INT(10)    COMMENT '状态 冻结' ,
    user_type VARCHAR(20)    COMMENT '用户类型 普通用户，管理员用户' ,
    CREATE_BY VARCHAR(32)    COMMENT '创建人' ,
    CREATE_DATE DATETIME    COMMENT '创建时间' ,
    UPDATE_BY VARCHAR(32)    COMMENT '修改人' ,
    UPDATE_DATE DATETIME    COMMENT '修改时间' ,
    REVISION INT(10)    COMMENT '乐观锁' ,
    PRIMARY KEY (USER_ID)
) COMMENT = '用户表 ';/*SQL@Run*/

CREATE TABLE RBAC_USER_ROLE(
    USER_ID VARCHAR(32)    COMMENT '用户ID' ,
    ROLE_ID VARCHAR(32)    COMMENT '角色ID' ,
    TENANT_ID VARCHAR(32)    COMMENT '租户ID' ,
    CREATE_BY VARCHAR(32)    COMMENT '创建人' ,
    CREATE_DATE DATETIME    COMMENT '创建时间' ,
    UPDATE_BY VARCHAR(32)    COMMENT '修改人' ,
    UPDATE_DATE DATETIME    COMMENT '修改时间' ,
    REVISION INT(10)    COMMENT '乐观锁'
) COMMENT = '用户角色关系表 ';/*SQL@Run*/