export default {
  'menu.demo': 'demo',
  'menu.demo.testAdd': '添加',
  'menu.demo.testList': '列表',
  'menu.homepage': '首页',
  'menu.account': '账户',
  'menu.account.logout':'退出',
  'menu.account.modifyPwd':'修改密码',
  'menu.contactRecordMgr': '交往管理',
  'menu.contactRecord': '交往记录',
  'menu.contactRecord.edit':'编辑交往记录',
  'menu.contactRecord.calendar': '交往日历',
  'menu.contact': '联系人管理',
  'menu.contactMgr': '联系人管理',
  'menu.contact.contactList': '联系人列表',
  'menu.contact.contactDetail': '联系人详情',
  'menu.contact.contactEdit': '联系人表单',
  'menu.tag': '标签管理',
  'menu.connectionsMgr': '人脉管理',
  'menu.tenantMgr': '租户管理',
  'menu.database': '数据库管理',
  'menu.database.add': '数据库添加',
  'menu.connectionsMgr.add': '人脉添加',
  'menu.connectionsMgr.graph': '人脉展示',
  'menu.logMgr': '日志管理',
  'menu.parCon': '参数配置管理',
};
