package net.chinahrd.dao;

import net.chinahrd.dto.VDimEmp;
import net.chinahrd.dto.VDimEmpExample;
import org.apache.ibatis.annotations.*;
import org.apache.ibatis.type.JdbcType;
import org.springframework.stereotype.Repository;

import java.util.List;

@Repository("vDimEmpMapper")
public interface VDimEmpMapper {
    @SelectProvider(type=VDimEmpSqlProvider.class, method="countByExample")
    long countByExample(VDimEmpExample example);

    @DeleteProvider(type=VDimEmpSqlProvider.class, method="deleteByExample")
    int deleteByExample(VDimEmpExample example);

    @Delete({
        "delete from v_dim_emp",
        "where emp_id = #{empId,jdbcType=VARCHAR}"
    })
    int deleteByPrimaryKey(String empId);

    @Insert({
        "insert into v_dim_emp (emp_id, customer_id, ",
        "emp_key, user_name, ",
        "user_name_ch, emp_hf_id, ",
        "emp_hf_key, report_relation, ",
        "email, img_path, ",
        "passtime_or_fulltime, contract, ",
        "blood, age, company_age, ",
        "is_key_talent, sex, nation, ",
        "degree_id, degree, native_place, ",
        "country, birth_place, ",
        "birth_date, national_id, ",
        "national_type, marry_status, ",
        "patty_name, position_id, ",
        "position_name, organization_parent_id, ",
        "organization_parent_name, organization_id, ",
        "organization_name, sequence_id, ",
        "sequence_name, sequence_sub_id, ",
        "sequence_sub_name, performance_id, ",
        "performance_name, ability_id, ",
        "job_title_id, ability_lv_id, ",
        "ability_name, job_title_name, ",
        "ability_lv_name, rank_name, ",
        "population_id, population_name, ",
        "area_id, run_off_date, entry_date, ",
        "tel_phone, qq, wx_code, ",
        "address, contract_unit, ",
        "work_place_id, work_place, ",
        "regular_date, apply_type, ",
        "channel_id, speciality, ",
        "is_regular, refresh_date, ",
        "c_id, mark, v_dim_emp_id)",
        "values (#{empId,jdbcType=VARCHAR}, #{customerId,jdbcType=CHAR}, ",
        "#{empKey,jdbcType=VARCHAR}, #{userName,jdbcType=VARCHAR}, ",
        "#{userNameCh,jdbcType=VARCHAR}, #{empHfId,jdbcType=CHAR}, ",
        "#{empHfKey,jdbcType=VARCHAR}, #{reportRelation,jdbcType=VARCHAR}, ",
        "#{email,jdbcType=VARCHAR}, #{imgPath,jdbcType=VARCHAR}, ",
        "#{passtimeOrFulltime,jdbcType=VARCHAR}, #{contract,jdbcType=VARCHAR}, ",
        "#{blood,jdbcType=VARCHAR}, #{age,jdbcType=DOUBLE}, #{companyAge,jdbcType=DOUBLE}, ",
        "#{isKeyTalent,jdbcType=BIT}, #{sex,jdbcType=CHAR}, #{nation,jdbcType=VARCHAR}, ",
        "#{degreeId,jdbcType=CHAR}, #{degree,jdbcType=VARCHAR}, #{nativePlace,jdbcType=VARCHAR}, ",
        "#{country,jdbcType=VARCHAR}, #{birthPlace,jdbcType=VARCHAR}, ",
        "#{birthDate,jdbcType=DATE}, #{nationalId,jdbcType=CHAR}, ",
        "#{nationalType,jdbcType=VARCHAR}, #{marryStatus,jdbcType=BIT}, ",
        "#{pattyName,jdbcType=VARCHAR}, #{positionId,jdbcType=CHAR}, ",
        "#{positionName,jdbcType=VARCHAR}, #{organizationParentId,jdbcType=CHAR}, ",
        "#{organizationParentName,jdbcType=VARCHAR}, #{organizationId,jdbcType=CHAR}, ",
        "#{organizationName,jdbcType=VARCHAR}, #{sequenceId,jdbcType=CHAR}, ",
        "#{sequenceName,jdbcType=VARCHAR}, #{sequenceSubId,jdbcType=CHAR}, ",
        "#{sequenceSubName,jdbcType=VARCHAR}, #{performanceId,jdbcType=CHAR}, ",
        "#{performanceName,jdbcType=VARCHAR}, #{abilityId,jdbcType=CHAR}, ",
        "#{jobTitleId,jdbcType=CHAR}, #{abilityLvId,jdbcType=CHAR}, ",
        "#{abilityName,jdbcType=VARCHAR}, #{jobTitleName,jdbcType=VARCHAR}, ",
        "#{abilityLvName,jdbcType=VARCHAR}, #{rankName,jdbcType=VARCHAR}, ",
        "#{populationId,jdbcType=CHAR}, #{populationName,jdbcType=VARCHAR}, ",
        "#{areaId,jdbcType=CHAR}, #{runOffDate,jdbcType=DATE}, #{entryDate,jdbcType=TIMESTAMP}, ",
        "#{telPhone,jdbcType=VARCHAR}, #{qq,jdbcType=VARCHAR}, #{wxCode,jdbcType=VARCHAR}, ",
        "#{address,jdbcType=VARCHAR}, #{contractUnit,jdbcType=VARCHAR}, ",
        "#{workPlaceId,jdbcType=CHAR}, #{workPlace,jdbcType=VARCHAR}, ",
        "#{regularDate,jdbcType=TIMESTAMP}, #{applyType,jdbcType=VARCHAR}, ",
        "#{channelId,jdbcType=CHAR}, #{speciality,jdbcType=VARCHAR}, ",
        "#{isRegular,jdbcType=VARCHAR}, #{refreshDate,jdbcType=TIMESTAMP}, ",
        "#{cId,jdbcType=VARCHAR}, #{mark,jdbcType=TINYINT}, #{vDimEmpId,jdbcType=CHAR})"
    })
    int insert(VDimEmp record);

    @InsertProvider(type=VDimEmpSqlProvider.class, method="insertSelective")
    int insertSelective(VDimEmp record);

    @SelectProvider(type=VDimEmpSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="emp_id", property="empId", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="customer_id", property="customerId", jdbcType=JdbcType.CHAR),
        @Result(column="emp_key", property="empKey", jdbcType=JdbcType.VARCHAR),
        @Result(column="user_name", property="userName", jdbcType=JdbcType.VARCHAR),
        @Result(column="user_name_ch", property="userNameCh", jdbcType=JdbcType.VARCHAR),
        @Result(column="emp_hf_id", property="empHfId", jdbcType=JdbcType.CHAR),
        @Result(column="emp_hf_key", property="empHfKey", jdbcType=JdbcType.VARCHAR),
        @Result(column="report_relation", property="reportRelation", jdbcType=JdbcType.VARCHAR),
        @Result(column="email", property="email", jdbcType=JdbcType.VARCHAR),
        @Result(column="img_path", property="imgPath", jdbcType=JdbcType.VARCHAR),
        @Result(column="passtime_or_fulltime", property="passtimeOrFulltime", jdbcType=JdbcType.VARCHAR),
        @Result(column="contract", property="contract", jdbcType=JdbcType.VARCHAR),
        @Result(column="blood", property="blood", jdbcType=JdbcType.VARCHAR),
        @Result(column="age", property="age", jdbcType=JdbcType.DOUBLE),
        @Result(column="company_age", property="companyAge", jdbcType=JdbcType.DOUBLE),
        @Result(column="is_key_talent", property="isKeyTalent", jdbcType=JdbcType.BIT),
        @Result(column="sex", property="sex", jdbcType=JdbcType.CHAR),
        @Result(column="nation", property="nation", jdbcType=JdbcType.VARCHAR),
        @Result(column="degree_id", property="degreeId", jdbcType=JdbcType.CHAR),
        @Result(column="degree", property="degree", jdbcType=JdbcType.VARCHAR),
        @Result(column="native_place", property="nativePlace", jdbcType=JdbcType.VARCHAR),
        @Result(column="country", property="country", jdbcType=JdbcType.VARCHAR),
        @Result(column="birth_place", property="birthPlace", jdbcType=JdbcType.VARCHAR),
        @Result(column="birth_date", property="birthDate", jdbcType=JdbcType.DATE),
        @Result(column="national_id", property="nationalId", jdbcType=JdbcType.CHAR),
        @Result(column="national_type", property="nationalType", jdbcType=JdbcType.VARCHAR),
        @Result(column="marry_status", property="marryStatus", jdbcType=JdbcType.BIT),
        @Result(column="patty_name", property="pattyName", jdbcType=JdbcType.VARCHAR),
        @Result(column="position_id", property="positionId", jdbcType=JdbcType.CHAR),
        @Result(column="position_name", property="positionName", jdbcType=JdbcType.VARCHAR),
        @Result(column="organization_parent_id", property="organizationParentId", jdbcType=JdbcType.CHAR),
        @Result(column="organization_parent_name", property="organizationParentName", jdbcType=JdbcType.VARCHAR),
        @Result(column="organization_id", property="organizationId", jdbcType=JdbcType.CHAR),
        @Result(column="organization_name", property="organizationName", jdbcType=JdbcType.VARCHAR),
        @Result(column="sequence_id", property="sequenceId", jdbcType=JdbcType.CHAR),
        @Result(column="sequence_name", property="sequenceName", jdbcType=JdbcType.VARCHAR),
        @Result(column="sequence_sub_id", property="sequenceSubId", jdbcType=JdbcType.CHAR),
        @Result(column="sequence_sub_name", property="sequenceSubName", jdbcType=JdbcType.VARCHAR),
        @Result(column="performance_id", property="performanceId", jdbcType=JdbcType.CHAR),
        @Result(column="performance_name", property="performanceName", jdbcType=JdbcType.VARCHAR),
        @Result(column="ability_id", property="abilityId", jdbcType=JdbcType.CHAR),
        @Result(column="job_title_id", property="jobTitleId", jdbcType=JdbcType.CHAR),
        @Result(column="ability_lv_id", property="abilityLvId", jdbcType=JdbcType.CHAR),
        @Result(column="ability_name", property="abilityName", jdbcType=JdbcType.VARCHAR),
        @Result(column="job_title_name", property="jobTitleName", jdbcType=JdbcType.VARCHAR),
        @Result(column="ability_lv_name", property="abilityLvName", jdbcType=JdbcType.VARCHAR),
        @Result(column="rank_name", property="rankName", jdbcType=JdbcType.VARCHAR),
        @Result(column="population_id", property="populationId", jdbcType=JdbcType.CHAR),
        @Result(column="population_name", property="populationName", jdbcType=JdbcType.VARCHAR),
        @Result(column="area_id", property="areaId", jdbcType=JdbcType.CHAR),
        @Result(column="run_off_date", property="runOffDate", jdbcType=JdbcType.DATE),
        @Result(column="entry_date", property="entryDate", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="tel_phone", property="telPhone", jdbcType=JdbcType.VARCHAR),
        @Result(column="qq", property="qq", jdbcType=JdbcType.VARCHAR),
        @Result(column="wx_code", property="wxCode", jdbcType=JdbcType.VARCHAR),
        @Result(column="address", property="address", jdbcType=JdbcType.VARCHAR),
        @Result(column="contract_unit", property="contractUnit", jdbcType=JdbcType.VARCHAR),
        @Result(column="work_place_id", property="workPlaceId", jdbcType=JdbcType.CHAR),
        @Result(column="work_place", property="workPlace", jdbcType=JdbcType.VARCHAR),
        @Result(column="regular_date", property="regularDate", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="apply_type", property="applyType", jdbcType=JdbcType.VARCHAR),
        @Result(column="channel_id", property="channelId", jdbcType=JdbcType.CHAR),
        @Result(column="speciality", property="speciality", jdbcType=JdbcType.VARCHAR),
        @Result(column="is_regular", property="isRegular", jdbcType=JdbcType.VARCHAR),
        @Result(column="refresh_date", property="refreshDate", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="c_id", property="cId", jdbcType=JdbcType.VARCHAR),
        @Result(column="mark", property="mark", jdbcType=JdbcType.TINYINT),
        @Result(column="v_dim_emp_id", property="vDimEmpId", jdbcType=JdbcType.CHAR)
    })
    List<VDimEmp> selectByExample(VDimEmpExample example);

    @Select({
        "select",
        "emp_id, customer_id, emp_key, user_name, user_name_ch, emp_hf_id, emp_hf_key, ",
        "report_relation, email, img_path, passtime_or_fulltime, contract, blood, age, ",
        "company_age, is_key_talent, sex, nation, degree_id, degree, native_place, country, ",
        "birth_place, birth_date, national_id, national_type, marry_status, patty_name, ",
        "position_id, position_name, organization_parent_id, organization_parent_name, ",
        "organization_id, organization_name, sequence_id, sequence_name, sequence_sub_id, ",
        "sequence_sub_name, performance_id, performance_name, ability_id, job_title_id, ",
        "ability_lv_id, ability_name, job_title_name, ability_lv_name, rank_name, population_id, ",
        "population_name, area_id, run_off_date, entry_date, tel_phone, qq, wx_code, ",
        "address, contract_unit, work_place_id, work_place, regular_date, apply_type, ",
        "channel_id, speciality, is_regular, refresh_date, c_id, mark, v_dim_emp_id",
        "from v_dim_emp",
        "where emp_id = #{empId,jdbcType=VARCHAR}"
    })
    @Results({
        @Result(column="emp_id", property="empId", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="customer_id", property="customerId", jdbcType=JdbcType.CHAR),
        @Result(column="emp_key", property="empKey", jdbcType=JdbcType.VARCHAR),
        @Result(column="user_name", property="userName", jdbcType=JdbcType.VARCHAR),
        @Result(column="user_name_ch", property="userNameCh", jdbcType=JdbcType.VARCHAR),
        @Result(column="emp_hf_id", property="empHfId", jdbcType=JdbcType.CHAR),
        @Result(column="emp_hf_key", property="empHfKey", jdbcType=JdbcType.VARCHAR),
        @Result(column="report_relation", property="reportRelation", jdbcType=JdbcType.VARCHAR),
        @Result(column="email", property="email", jdbcType=JdbcType.VARCHAR),
        @Result(column="img_path", property="imgPath", jdbcType=JdbcType.VARCHAR),
        @Result(column="passtime_or_fulltime", property="passtimeOrFulltime", jdbcType=JdbcType.VARCHAR),
        @Result(column="contract", property="contract", jdbcType=JdbcType.VARCHAR),
        @Result(column="blood", property="blood", jdbcType=JdbcType.VARCHAR),
        @Result(column="age", property="age", jdbcType=JdbcType.DOUBLE),
        @Result(column="company_age", property="companyAge", jdbcType=JdbcType.DOUBLE),
        @Result(column="is_key_talent", property="isKeyTalent", jdbcType=JdbcType.BIT),
        @Result(column="sex", property="sex", jdbcType=JdbcType.CHAR),
        @Result(column="nation", property="nation", jdbcType=JdbcType.VARCHAR),
        @Result(column="degree_id", property="degreeId", jdbcType=JdbcType.CHAR),
        @Result(column="degree", property="degree", jdbcType=JdbcType.VARCHAR),
        @Result(column="native_place", property="nativePlace", jdbcType=JdbcType.VARCHAR),
        @Result(column="country", property="country", jdbcType=JdbcType.VARCHAR),
        @Result(column="birth_place", property="birthPlace", jdbcType=JdbcType.VARCHAR),
        @Result(column="birth_date", property="birthDate", jdbcType=JdbcType.DATE),
        @Result(column="national_id", property="nationalId", jdbcType=JdbcType.CHAR),
        @Result(column="national_type", property="nationalType", jdbcType=JdbcType.VARCHAR),
        @Result(column="marry_status", property="marryStatus", jdbcType=JdbcType.BIT),
        @Result(column="patty_name", property="pattyName", jdbcType=JdbcType.VARCHAR),
        @Result(column="position_id", property="positionId", jdbcType=JdbcType.CHAR),
        @Result(column="position_name", property="positionName", jdbcType=JdbcType.VARCHAR),
        @Result(column="organization_parent_id", property="organizationParentId", jdbcType=JdbcType.CHAR),
        @Result(column="organization_parent_name", property="organizationParentName", jdbcType=JdbcType.VARCHAR),
        @Result(column="organization_id", property="organizationId", jdbcType=JdbcType.CHAR),
        @Result(column="organization_name", property="organizationName", jdbcType=JdbcType.VARCHAR),
        @Result(column="sequence_id", property="sequenceId", jdbcType=JdbcType.CHAR),
        @Result(column="sequence_name", property="sequenceName", jdbcType=JdbcType.VARCHAR),
        @Result(column="sequence_sub_id", property="sequenceSubId", jdbcType=JdbcType.CHAR),
        @Result(column="sequence_sub_name", property="sequenceSubName", jdbcType=JdbcType.VARCHAR),
        @Result(column="performance_id", property="performanceId", jdbcType=JdbcType.CHAR),
        @Result(column="performance_name", property="performanceName", jdbcType=JdbcType.VARCHAR),
        @Result(column="ability_id", property="abilityId", jdbcType=JdbcType.CHAR),
        @Result(column="job_title_id", property="jobTitleId", jdbcType=JdbcType.CHAR),
        @Result(column="ability_lv_id", property="abilityLvId", jdbcType=JdbcType.CHAR),
        @Result(column="ability_name", property="abilityName", jdbcType=JdbcType.VARCHAR),
        @Result(column="job_title_name", property="jobTitleName", jdbcType=JdbcType.VARCHAR),
        @Result(column="ability_lv_name", property="abilityLvName", jdbcType=JdbcType.VARCHAR),
        @Result(column="rank_name", property="rankName", jdbcType=JdbcType.VARCHAR),
        @Result(column="population_id", property="populationId", jdbcType=JdbcType.CHAR),
        @Result(column="population_name", property="populationName", jdbcType=JdbcType.VARCHAR),
        @Result(column="area_id", property="areaId", jdbcType=JdbcType.CHAR),
        @Result(column="run_off_date", property="runOffDate", jdbcType=JdbcType.DATE),
        @Result(column="entry_date", property="entryDate", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="tel_phone", property="telPhone", jdbcType=JdbcType.VARCHAR),
        @Result(column="qq", property="qq", jdbcType=JdbcType.VARCHAR),
        @Result(column="wx_code", property="wxCode", jdbcType=JdbcType.VARCHAR),
        @Result(column="address", property="address", jdbcType=JdbcType.VARCHAR),
        @Result(column="contract_unit", property="contractUnit", jdbcType=JdbcType.VARCHAR),
        @Result(column="work_place_id", property="workPlaceId", jdbcType=JdbcType.CHAR),
        @Result(column="work_place", property="workPlace", jdbcType=JdbcType.VARCHAR),
        @Result(column="regular_date", property="regularDate", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="apply_type", property="applyType", jdbcType=JdbcType.VARCHAR),
        @Result(column="channel_id", property="channelId", jdbcType=JdbcType.CHAR),
        @Result(column="speciality", property="speciality", jdbcType=JdbcType.VARCHAR),
        @Result(column="is_regular", property="isRegular", jdbcType=JdbcType.VARCHAR),
        @Result(column="refresh_date", property="refreshDate", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="c_id", property="cId", jdbcType=JdbcType.VARCHAR),
        @Result(column="mark", property="mark", jdbcType=JdbcType.TINYINT),
        @Result(column="v_dim_emp_id", property="vDimEmpId", jdbcType=JdbcType.CHAR)
    })
    VDimEmp selectByPrimaryKey(String empId);

    @UpdateProvider(type=VDimEmpSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") VDimEmp record, @Param("example") VDimEmpExample example);

    @UpdateProvider(type=VDimEmpSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") VDimEmp record, @Param("example") VDimEmpExample example);

    @UpdateProvider(type=VDimEmpSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(VDimEmp record);

    @Update({
        "update v_dim_emp",
        "set customer_id = #{customerId,jdbcType=CHAR},",
          "emp_key = #{empKey,jdbcType=VARCHAR},",
          "user_name = #{userName,jdbcType=VARCHAR},",
          "user_name_ch = #{userNameCh,jdbcType=VARCHAR},",
          "emp_hf_id = #{empHfId,jdbcType=CHAR},",
          "emp_hf_key = #{empHfKey,jdbcType=VARCHAR},",
          "report_relation = #{reportRelation,jdbcType=VARCHAR},",
          "email = #{email,jdbcType=VARCHAR},",
          "img_path = #{imgPath,jdbcType=VARCHAR},",
          "passtime_or_fulltime = #{passtimeOrFulltime,jdbcType=VARCHAR},",
          "contract = #{contract,jdbcType=VARCHAR},",
          "blood = #{blood,jdbcType=VARCHAR},",
          "age = #{age,jdbcType=DOUBLE},",
          "company_age = #{companyAge,jdbcType=DOUBLE},",
          "is_key_talent = #{isKeyTalent,jdbcType=BIT},",
          "sex = #{sex,jdbcType=CHAR},",
          "nation = #{nation,jdbcType=VARCHAR},",
          "degree_id = #{degreeId,jdbcType=CHAR},",
          "degree = #{degree,jdbcType=VARCHAR},",
          "native_place = #{nativePlace,jdbcType=VARCHAR},",
          "country = #{country,jdbcType=VARCHAR},",
          "birth_place = #{birthPlace,jdbcType=VARCHAR},",
          "birth_date = #{birthDate,jdbcType=DATE},",
          "national_id = #{nationalId,jdbcType=CHAR},",
          "national_type = #{nationalType,jdbcType=VARCHAR},",
          "marry_status = #{marryStatus,jdbcType=BIT},",
          "patty_name = #{pattyName,jdbcType=VARCHAR},",
          "position_id = #{positionId,jdbcType=CHAR},",
          "position_name = #{positionName,jdbcType=VARCHAR},",
          "organization_parent_id = #{organizationParentId,jdbcType=CHAR},",
          "organization_parent_name = #{organizationParentName,jdbcType=VARCHAR},",
          "organization_id = #{organizationId,jdbcType=CHAR},",
          "organization_name = #{organizationName,jdbcType=VARCHAR},",
          "sequence_id = #{sequenceId,jdbcType=CHAR},",
          "sequence_name = #{sequenceName,jdbcType=VARCHAR},",
          "sequence_sub_id = #{sequenceSubId,jdbcType=CHAR},",
          "sequence_sub_name = #{sequenceSubName,jdbcType=VARCHAR},",
          "performance_id = #{performanceId,jdbcType=CHAR},",
          "performance_name = #{performanceName,jdbcType=VARCHAR},",
          "ability_id = #{abilityId,jdbcType=CHAR},",
          "job_title_id = #{jobTitleId,jdbcType=CHAR},",
          "ability_lv_id = #{abilityLvId,jdbcType=CHAR},",
          "ability_name = #{abilityName,jdbcType=VARCHAR},",
          "job_title_name = #{jobTitleName,jdbcType=VARCHAR},",
          "ability_lv_name = #{abilityLvName,jdbcType=VARCHAR},",
          "rank_name = #{rankName,jdbcType=VARCHAR},",
          "population_id = #{populationId,jdbcType=CHAR},",
          "population_name = #{populationName,jdbcType=VARCHAR},",
          "area_id = #{areaId,jdbcType=CHAR},",
          "run_off_date = #{runOffDate,jdbcType=DATE},",
          "entry_date = #{entryDate,jdbcType=TIMESTAMP},",
          "tel_phone = #{telPhone,jdbcType=VARCHAR},",
          "qq = #{qq,jdbcType=VARCHAR},",
          "wx_code = #{wxCode,jdbcType=VARCHAR},",
          "address = #{address,jdbcType=VARCHAR},",
          "contract_unit = #{contractUnit,jdbcType=VARCHAR},",
          "work_place_id = #{workPlaceId,jdbcType=CHAR},",
          "work_place = #{workPlace,jdbcType=VARCHAR},",
          "regular_date = #{regularDate,jdbcType=TIMESTAMP},",
          "apply_type = #{applyType,jdbcType=VARCHAR},",
          "channel_id = #{channelId,jdbcType=CHAR},",
          "speciality = #{speciality,jdbcType=VARCHAR},",
          "is_regular = #{isRegular,jdbcType=VARCHAR},",
          "refresh_date = #{refreshDate,jdbcType=TIMESTAMP},",
          "c_id = #{cId,jdbcType=VARCHAR},",
          "mark = #{mark,jdbcType=TINYINT},",
          "v_dim_emp_id = #{vDimEmpId,jdbcType=CHAR}",
        "where emp_id = #{empId,jdbcType=VARCHAR}"
    })
    int updateByPrimaryKey(VDimEmp record);
}